# Generated by Django 4.2.4 on 2023-08-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='Receipe_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='Receipe_image',
            new_name='receipe_image',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='Receipe_name',
            new_name='receipe_name',
        ),
    ]
